const scenarios = [
  {
    id: 'ecommerce',
    name: 'E-Commerce',
    icon: '🛒',
    subtitle: 'Holiday Flash Sale',
    description:
      'Manage pricing for wireless headphones during a holiday flash sale. Balance demand and inventory across 30 rounds to maximize revenue.',
    basePrice: 79,
    minPrice: 29,
    maxPrice: 149,
    initialInventory: 200,
    elasticity: 1.4,
    timeLimit: 30,
    optimalRevenue: 4200,
    sentimentBase: 70,
    demandBase: 12,
    unit: 'units',
  },
  {
    id: 'rideshare',
    name: 'Ride-Share',
    icon: '🚗',
    subtitle: 'Friday Night Surge',
    description:
      'Set surge pricing for rides on a busy Friday night. Higher prices reduce demand but increase per-ride revenue.',
    basePrice: 15,
    minPrice: 8,
    maxPrice: 45,
    initialInventory: 80,
    elasticity: 1.1,
    timeLimit: 30,
    optimalRevenue: 1800,
    sentimentBase: 70,
    demandBase: 8,
    unit: 'rides',
  },
  {
    id: 'hotel',
    name: 'Hotel',
    icon: '🏨',
    subtitle: 'Convention Weekend',
    description:
      'Price hotel rooms during a high-demand convention weekend. Low elasticity means guests are less price-sensitive.',
    basePrice: 180,
    minPrice: 89,
    maxPrice: 450,
    initialInventory: 60,
    elasticity: 0.9,
    timeLimit: 30,
    optimalRevenue: 8500,
    sentimentBase: 70,
    demandBase: 5,
    unit: 'rooms',
  },
  {
    id: 'events',
    name: 'Event Tickets',
    icon: '🎵',
    subtitle: 'Summer Music Festival',
    description:
      'Sell tickets for a summer music festival. High elasticity and large inventory — pricing decisions have outsized impact.',
    basePrice: 120,
    minPrice: 49,
    maxPrice: 299,
    initialInventory: 500,
    elasticity: 1.6,
    timeLimit: 30,
    optimalRevenue: 28000,
    sentimentBase: 70,
    demandBase: 25,
    unit: 'tickets',
  },
];

export default scenarios;
