const scenarios = [
  {
    id: 'ecommerce',
    name: 'E-Commerce',
    icon: '🛒',
    subtitle: 'Holiday Flash Sale',
    description:
      'Manage pricing for wireless headphones during a holiday flash sale. Outprice your competitor across 50 rounds to maximize revenue.',
    basePrice: 79,
    minPrice: 29,
    maxPrice: 149,
    initialInventory: 200,
    elasticity: 1.4,
    timeLimit: 50,
    optimalRevenue: 7000,
    sentimentBase: 70,
    demandBase: 12,
    competitorBase: 79,
    unit: 'units',
  },
  {
    id: 'rideshare',
    name: 'Ride-Share',
    icon: '🚗',
    subtitle: 'Friday Night Surge',
    description:
      'Set surge pricing for rides on a busy Friday night. A rival service adjusts its fares in response to yours.',
    basePrice: 15,
    minPrice: 8,
    maxPrice: 45,
    initialInventory: 80,
    elasticity: 1.1,
    timeLimit: 50,
    optimalRevenue: 3000,
    sentimentBase: 70,
    demandBase: 8,
    competitorBase: 15,
    unit: 'rides',
  },
  {
    id: 'hotel',
    name: 'Hotel',
    icon: '🏨',
    subtitle: 'Convention Weekend',
    description:
      'Price hotel rooms during a high-demand convention weekend. A competing hotel across the street is watching your rates.',
    basePrice: 180,
    minPrice: 89,
    maxPrice: 450,
    initialInventory: 60,
    elasticity: 0.9,
    timeLimit: 50,
    optimalRevenue: 14000,
    sentimentBase: 70,
    demandBase: 5,
    competitorBase: 180,
    unit: 'rooms',
  },
  {
    id: 'events',
    name: 'Event Tickets',
    icon: '🎵',
    subtitle: 'Summer Music Festival',
    description:
      'Sell tickets for a summer music festival. A rival venue is running a competing event at the same time.',
    basePrice: 120,
    minPrice: 49,
    maxPrice: 299,
    initialInventory: 500,
    elasticity: 1.6,
    timeLimit: 50,
    optimalRevenue: 46000,
    sentimentBase: 70,
    demandBase: 25,
    competitorBase: 120,
    unit: 'tickets',
  },
];

export default scenarios;
